# Generated by Django 4.2.5 on 2023-10-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_compony_user_email_user_phone_alter_user_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='compony',
            new_name='company',
        ),
    ]
