# Generated by Django 4.2.5 on 2023-10-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userexclusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexclusion',
            old_name='user',
            new_name='username',
        ),
    ]
