# Generated by Django 4.2.5 on 2023-10-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_userexclusion_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExclusion',
        ),
    ]
